#!/usr/bin/env bash
if [ ! -e /develop/workspace/project ]; then
	cp -a /develop/archive/workspace/project /develop/workspace/
fi
# ACCONとサンプルの設置
if [ ! -e /develop/workspace/project/fuel/app/modules/accon ]; then
	# ACCON
	curl -k https://kurobuta.jp/download/get/6 > /develop/archive/accon.zip
	unzip /develop/archive/accon.zip -d /develop/workspace/project/fuel/app/modules
	# SAMPLE
	curl -k https://kurobuta.jp/download/get/16 > /develop/archive/sample.zip
	unzip -o /develop/archive/sample.zip -d /develop/workspace/project/
	rm -Rf /develop/workspace/project/public/assets
	mv /develop/workspace/project/fuel/public/assets /develop/workspace/project/public/
	mv -f /develop/workspace/project/fuel/public/.htaccess /develop/workspace/project/public/
	rm -Rf /develop/workspace/project/fuel/public
	# 初期データの設置
	cp /develop/workspace/project/fuel/app/modules/accon/initial/data/database.sql /develop/data/
	cp /develop/workspace/project/fuel/app/modules/accon/initial/data/tables.sql /develop/data/
fi
# download
if [ ! -e /develop/workspace/project/fuel/app/modules/menus ]; then
	curl -k https://kurobuta.jp/download/get/13 > /develop/archive/menus.zip
	unzip /develop/archive/menus.zip -d /develop/workspace/project/fuel/app/modules
fi
# books
if [ ! -e /develop/workspace/project/fuel/app/modules/treebooks ]; then
	curl -k https://kurobuta.jp/download/get/14 > /develop/archive/treebooks.zip
	unzip /develop/archive/treebooks.zip -d /develop/workspace/project/fuel/app/modules
fi
# download
if [ ! -e /develop/workspace/project/fuel/app/modules/download ]; then
	curl -k https://kurobuta.jp/download/get/7 > /develop/archive/download.zip
	unzip /develop/archive/download.zip -d /develop/workspace/project/fuel/app/modules
fi
# wwwの設置
if [ ! -e /develop/www/index.php ]; then
	ln -s /develop/workspace/project/public/* /develop/www/
	ln -s /develop/workspace/project/public/.htaccess /develop/www/
fi
echo " * ACCON Installation completion"
/etc/service/run



